version: '3.9'
services:
  hermes-foods-app:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: go-hermes-foods-app
    depends_on:
      - postgresdb
    env_file: "./.env"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      default:
        ipv4_address: 204.7.9.2
        
  postgresdb:
    image: "postgres"
    container_name: postgresql-hermes-foods
    env_file: "./.env"
    tty: true
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/infrastructure/scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      default:
        ipv4_address: 204.7.9.3

  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger_hermes_foods
    env_file: ./.env
    ports:
      - "8083:8080"
    volumes:
      - ${PWD}/infrastructure/swagger_doc/swagger.json:/swagger.json
    networks:
      default:
        ipv4_address: 204.7.9.4

networks:
  default:
    external: true
    name: hermes_foods_net_dev
