# Deployment config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-foods-postgres-deployment
  namespace: dev
  labels:
    app: hermes-foods-postgres-app

spec:
  replicas: 1 

  selector:
    matchLabels:
      app: hermes-foods-postgres-app 

  template:
    metadata:
      labels:
        app: hermes-foods-postgres-app
    spec:
      containers:
      - name: postgresql-hermes-foods
        image: "{{REPOSITORY_POSTGRES_URL}}:{{IMAGE_TAG}}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: hf-deploy-secret
        volumeMounts:
        - name: shared
          mountPath: ./docker-entrypoint-initdb.d/init-database.sh

      imagePullSecrets:
      - name: hfregcred

      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: hf-pv-claim-postgres

---

# Service config
apiVersion: v1
kind: Service
metadata:
  name: hermes-foods-postgres-service
  namespace: dev

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hermes-foods-postgres-app 

  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432 
