apiVersion: v1
kind: ConfigMap
metadata:
  name: hf-postgres-init-db
  namespace: dev

data:
  init-database.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE $DB_NAME;
        SELECT session_user, current_database();
        DROP USER IF EXISTS $DB_USER;
        CREATE USER $DB_USER LOGIN PASSWORD '$DB_PASSWORD';
        GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
        GRANT USAGE, CREATE ON SCHEMA public TO $DB_USER;
        ALTER DATABASE $DB_NAME OWNER TO $DB_USER;
    EOSQL
