# Deployment config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-foods-go-deployment
  namespace: dev
  labels:
    app: hermes-foods-go-app

spec:
  replicas: 1 # It specifies how many pods do you wanna create with the specs below.

  selector:
    matchLabels:
      app: hermes-foods-go-app # This label references the label that we specified in line 7, bcz it maches from deployment label.

  template:
    metadata:
      labels:
        app: hermes-foods-go-app
    spec:
      containers:
      - name: go-hermes-foods-app
        image: "${REPOSITORY_API_URL}:${IMAGE_TAG}"
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: hf-deploy-secret
        ports:
        - containerPort: 8080
        - containerPort: 8081
      imagePullSecrets:
      - name: hfregcred

---

# Service config
apiVersion: v1
kind: Service
metadata:
  name: hermes-foods-go-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: hermes-foods-go-app # It should be the same label as we defined in deployment config, so it belongs to "hermes-foods-go-app".
  ports:
    - protocol: TCP
      name: go-api-port
      port: 8080
      targetPort: 8080 # The same as container port defined in deployment
      nodePort: 30800
    - protocol: TCP
      name: api-fake-mp-port
      port: 8081
      targetPort: 8081 # The same as container port defined in deployment
      nodePort: 30801
