# Deployment config
apiVersion: v1
kind: Deployment
metadata:
  name: hermes-foods-swagger-deployment
  namespace: dev
  labels:
    app: hermes-foods-swagger-app

spec:
  replicas: 1 # It specifies how many pods do you wanna create with the specs below.

  selector:
    matchLabels:
      app: hermes-foods-swagger-app # This label references the label that we specified in line 7, bcz it maches from deployment label.

  template:
    metadata:
      labels:
        app: hermes-foods-swagger-app
    spec:
      containers:
      - name: swagger-hermes-foods
        image: hermes-foods-swagger:latest
        ports:
        - containerPort: 8083
        envFrom:
          - secretRef:
            name: hf-deploy-secret

---

# Service config
apiVersion: v1
kind: Service
metadata:
  name: hermes-foods-swagger-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: hermes-foods-swagger-app # It should be the same label as we defined in deployment config, so it belongs to "hermes-foods-swagger-app".
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8083 # The same as container port defined in deployment
      nodePort: 30803
