---
name: Build and Push Golang Image to AWS ECR
on:
  push:
    branches: [ main ]

jobs:
  hf-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build-and-push:
    name: Build and Push to ECR
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Configure credentials AWS ECR
      uses: aws-actions/configure-aws-credentials@v3
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ACTIONS_ROLE }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create .env
      run: |
         echo "${{ secrets.ENV_FILE }}" | base64 -d - > .env

          if [ -d $HOME/envs ]; then 
            echo ""
          else
            mkdir $HOME/envs
          fi
          mv .env $HOME/envs/.env
      shell: bash
        
    - name: Create docker network
      run: | 
          ls -la
          ./infrastructure/scripts/docker-network.sh
      shell: bash

    - name: Build, Tag, and Push images to Amazon ECR
      id: build-images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_API: hermes-foods-go
        ECR_REPOSITORY_SWAGGER: hermes-foods-swagger
        IMAGE_TAG: latest
      run: |
        cp /home/admin/envs/.env .
        docker build -f ./infrastructure/docker/Dockerfile.go_app -t $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_TAG
                
        docker build -f ./infrastructure/docker/Dockerfile.swagger -t $ECR_REGISTRY/$ECR_REPOSITORY_SWAGGER:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_SWAGGER:$IMAGE_TAG

    - name: Set up kubectl
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_FILE }}

    - name: K8s setup
      env:
        REPOSITORY_API_URL: ${{ secrets.AWS_REGISTRY_API_URL }}
        REPOSITORY_SWAGGER_URL: ${{ secrets.AWS_REGISTRY_SWAGGER_URL }}
        IMAGE_TAG: latest
      run: | 
          ./infrastructure/scripts/kubernetes-config.sh ${{ secrets.KUBE_REG_SERVER }} ${{ secrets.KUBE_REG_USERNAME }} ${{ secrets.KUBE_REG_PASSWORD }} ${{ secrets.KUBE_REG_EMAIL }}
          kubectl apply -f ./infrastructure/kubernetes/config/swagger.yaml
          kubectl apply -f ./infrastructure/kubernetes/deployment/app.yaml
          kubectl apply -f ./infrastructure/kubernetes/deployment/swagger.yaml
          kubectl apply -f ./infrastructure/kubernetes/hpa/app.yaml
          kubectl apply -f ./infrastructure/kubernetes/hpa/swagger.yaml
      shell: bash

    - name: Update pods
      run: | 
          kubectl rollout restart deployment hermes-foods-go-deployment -n dev
          kubectl rollout restart deployment hermes-foods-swagger-deployment -n dev
      shell: bash
