apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hermes-foods-postgres-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hermes-foods-postgres-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70