apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hermes-foods-swagger-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hermes-foods-swagger-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70